spring:
  application:
    name:
      registry

server:
  port:
    8761
  wait-time-in-ms-when-sync-empty: 0
  wait-time-in-ms: 500

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address:false  #for docker to work set to true
